spring:
  application:
    name: booking-api
  profiles:
    active: local
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bookingdb;INIT=runscript from 'classpath:init.sql'
  sql:
    init:
      mode: always